### ISSUE TITLE
**Capstone MVP Checklist** 

### ISSUE THREAD

**Issue by ghost** [ConnorSullivan10/guitarchive#7]
# User Story
As a developer in cohort E10, I need to follow the criteria below to meet the minimum viable product for my Capstone Front-End Project

# AC
- [x] Seed Data #1
- [x] Authentication #3
- [x] Read Brands #2
- [x] Read Guitars #6
- [x] Read on UserGuitars #8
- [x] Create on User Guitars #10 
- [x] Update on User Guitars #11
- [x] Delete on User Guitars #9
